### ISSUE TITLE
Cloud extensions?

### ISSUE THREAD

**Issue by teekaay** [otto-de/turing-microservice#7]
# Motivation

Following the new cloud extensions of the edison microservice (`edison-aws`), it would be useful
to provide the same or similar packages for the turing ecosystem.

# Possible features

- DynamoDB wrapper (alternative to turing-mongo)
- S3 client for fetching configuration data or similar
- CloudWatch metrics reporter

**Comment by BeneStem** [comment]
Atm there is no plan to do this. All of out teams node js projects will result in lambda functions without any application side server layer...

**Comment by BeneStem** [comment]
Atm there is no plan to do this. All of out teams node js projects will result in lambda functions without any application side server layer...

**Comment by BeneStem** [comment]
Atm there is no plan to do this. All of our teams node js projects will result in lambda functions without any application side server layer...
